config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :postagems do
      resources :criticas
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root :to => redirect('/postagems')
    root to: "home#index"  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       
       if user.admin?
         can :manage, :all
       else
         can [:create,:read], :Critica
         can :read , :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/critica.rb
class Critica < ApplicationRecord
  belongs_to :postagem
  validates_presence_of :post
  
end

app/models/postagem.rb
class Postagem < ApplicationRecord
    has_many :criticas, :dependent => :destroy
    validates_presence_of :titulo, :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cine_controller.rb
class CineControler < AplicationController
    def page
        
    end
    
    
end

app/controllers/criticas_controller.rb
class CriticasController < ApplicationController
    before_action :set_postagem

    def create
        @postagem.criticas.create! criticas_params
        redirect_to @postagem
    end


    private
    def set_postagem
        @postagem = Postagem.find(params[:postagem_id])
    end

    def criticas_params
        params.required(:critica).permit(:post)
    end
end

app/controllers/postagems_controller.rb
class PostagemsController < ApplicationController
  before_action :set_postagem, only: [:show, :edit, :update, :destroy]

  # GET /postagems
  # GET /postagems.json
  def index
    @postagems = Postagem.all
  end

  # GET /postagems/1
  # GET /postagems/1.json
  def show
  end

  # GET /postagems/new
  def new
    @postagem = Postagem.new
  end

  # GET /postagems/1/edit
  def edit
  end

  # POST /postagems
  # POST /postagems.json
  def create
    @postagem = Postagem.new(postagem_params)

    respond_to do |format|
      if @postagem.save
        format.html { redirect_to @postagem, notice: 'Postagem foi criada.' }
        format.json { render :show, status: :created, location: @postagem }
      else
        format.html { render :new }
        format.json { render json: @postagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postagems/1
  # PATCH/PUT /postagems/1.json
  def update
    respond_to do |format|
      if @postagem.update(postagem_params)
        format.html { redirect_to @postagem, notice: 'Postagem foi editada.' }
        format.json { render :show, status: :ok, location: @postagem }
      else
        format.html { render :edit }
        format.json { render json: @postagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postagems/1
  # DELETE /postagems/1.json
  def destroy
    @postagem.destroy
    respond_to do |format|
      format.html { redirect_to postagems_url, notice: 'Postagem foi destruida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postagem
      @postagem = Postagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postagem_params
      params.require(:postagem).permit(:titulo, :post)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criticas_helper.rb
module CriticasHelper
end

app/helpers/críticas_helper.rb
module CríticasHelper
end

app/helpers/postagems_helper.rb
module PostagemsHelper
end

app/views/criticas/_critica.html.erb
<p><%= critica.post %> -- <%= critica.created_at.to_s(:long) %> </p> 

app/views/criticas/_new.html.erb
 <%= form_for([ @postagem, Critica.new ], remote: true) do |form| %>
    Sua crítica: <br>
    <%= form.text_area :post, size: '50x20' %><br>
    <%= form.submit %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
  <%= link_to('Editar_registro', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  <%= link_to "Sing_Up", new_user_registration_path %>
  </li>
<% end %>

<div class = "creditos" > site da imagem de fundo <a href='http://allswalls.com'>http://allswalls.com</a> </div>
    <%= yield %>
  </body>
</html>

app/views/postagems/_form.html.erb
<%= form_with(model: postagem, local: true) do |form| %>
  <% if postagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postagem.errors.count, "error") %> prohibited this postagem from being saved:</h2>

      <ul>
      <% postagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :postagem_titulo %>
  </div>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post, id: :postagem_post %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/postagems/edit.html.erb
<h1>Editando Postagem</h1>

<%= render 'form', postagem: @postagem %>

<%= link_to 'Mostrar', @postagem %> |
<%= link_to 'Voltar', postagems_path %>

app/views/postagems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CineForum</h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Gênero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postagems.each do |postagem| %>
      <tr>
        <td><%= postagem.titulo %></td>
        <td><%= postagem.post %></td>
        <td><%= link_to 'Mostrar', postagem %></td>
        <% if can? :manage, Postagem %>
         <td><%= link_to 'Editar', edit_postagem_path(postagem) %></td>
         <td><%= link_to 'Destruir', postagem, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, Postagem %>
 <%= link_to 'Nova Postagem', new_postagem_path %>
<% end %>

app/views/postagems/new.html.erb
<h1>Nova Postagem</h1>

<%= render 'form', postagem: @postagem %>

<%= link_to 'Voltar', postagems_path %>

app/views/postagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @postagem.titulo %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @postagem.post %>
</p>
<% if can? :manage, Postagem %>
 <%= link_to 'Editar', edit_postagem_path(@postagem) %>
<% end %>

<%= link_to 'Voltar', postagems_path %>

<br><br>

<h2>Críticas</h2>

    <div id="criticas">
        <%# Expands to render partial: 'criticas/critica' , collection: @postagem.criticas %>
        <%= render @postagem.criticas %>
    </div>
    
    <%= render 'criticas/new', postagem: @postagem %>
</div>